function Untitled = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("D:\Mega\Dati\SurfaceStorica\Surface_Giornaliera_EUR\2017-10-31.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jan-2021 09:54:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["DATE", "DATE1", "ASKPRICE", "BIDPRICE", "OPTSTRIKEPRICE", "OPENINTEREST", "OPTEXERCISEPRICE", "PRICEHIGH", "PRICELOW", "OPENINGPRICE", "Instrument", "exp_date", "type"];
opts.VariableTypes = ["datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "string", "datetime", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd");
%opts = setvaropts(opts, "DATE1", "InputFormat", "yyyy-MM-dd");
%opts = setvaropts(opts, "exp_date", "InputFormat", "yyyy-MM-dd");

% Import the data
Untitled = readtable(filename, opts);

end